### ISSUE TITLE
PyInstaller 5.13.2 not published to conda-forge

### ISSUE THREAD

**Issue by ejwcobra** [conda-forge/pyinstaller-feedstock#102]
### Comment:

I’m trying to upgrade to PyInstaller 5.13.2, but that version doesn’t exist in conda-forge. However, I do see 5.13.0, as well as nearly every other PyInstaller version. Could PyInstaller 5.13.2 be published to conda-forge?
https://anaconda.org/conda-forge/pyinstaller/files

After poking around a little, I found this PR that was auto-closed by a bot.
https://github.com/conda-forge/pyinstaller-feedstock/pull/98

**Comment by nicoddemus** [comment]
Gave another attempt to #98, however build is failing due to an error in conda.

**Comment by ejwcobra** [comment]
5.13.2 published successfully
